name: Pyrefly Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b 

      - name: Setup uv project.
        run: uv sync --locked --all-extras --dev

      - name: Install pyrefly
        run: |
          uvx pyrefly init
      - name: Run pyrefly
        run: |
          uvx pyrefly check --output-format=github
